### ISSUE TITLE
Options help/height

### ISSUE THREAD

**Issue by Kochise** [prantlf/nomnoml-cli#21]
Options:

    **-h**, --help             output usage information
    **-h**, --height <pixels>  height of the canvas to draw on

Doubtful I am...

Maybe like the V/version, using upper case H for help would disambiguate things enough.

**Comment by prantlf** [comment]
Thanks a lot for reporting this bug. It shows how often I needed the `height` options :-)

Fixed in the [3.0.0 release](https://github.com/prantlf/nomnoml-cli/releases/tag/v3.0.0) as you suggested - with `-H` for the height. I am sorry for the long delay.
